#!/bin/bash
# Ralph AFK Loop Script with Full Feedback Loops
# Runs Claude in Docker sandbox with comprehensive quality checks
# Supports Python (venv/uv) and Node.js (pnpm) projects

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <iterations>"
  echo "Example: $0 20"
  exit 1
fi

# Ensure review.txt exists
if [ ! -f "review.txt" ]; then
  echo "# Code Review Log" > review.txt
  echo "# Generated by Ralph Loop with Feedback" >> review.txt
  echo "# Date: $(date '+%Y-%m-%d')" >> review.txt
  echo "" >> review.txt
fi

# Ensure progress.txt exists
if [ ! -f "progress.txt" ]; then
  echo "# Progress Log" > progress.txt
  echo "# Generated by Ralph Loop" >> progress.txt
  echo "# Date: $(date '+%Y-%m-%d')" >> progress.txt
  echo "" >> progress.txt
fi

echo "=========================================="
echo "Ralph Loop with Full Feedback Loops"
echo "=========================================="
echo "Iterations: $1"
echo "Model: Claude Opus (latest)"
echo ""
echo "Feedback Loops Enabled:"
echo "  - Type checking (mypy/pyright or tsc)"
echo "  - Unit tests (pytest or jest/vitest)"
echo "  - Linting (ruff/flake8 or eslint)"
echo "  - Pre-commit validation"
echo "=========================================="
echo ""

for ((i=1; i<=$1; i++)); do
  echo "=== Iteration $i of $1 ==="
  echo "Starting fresh Claude context..."
  echo ""

  result=$(docker sandbox run claude -- --model opus --permission-mode bypassPermissions --dangerously-skip-permissions -p "@prd.json @progress.txt @review.txt

========================================
QUALITY EXPECTATIONS
========================================
This codebase will outlive you. Every shortcut you take becomes
someone else's burden. Every hack compounds into technical debt
that slows the whole team down.

You are not just writing code. You are shaping the future of this
project. The patterns you establish will be copied. The corners
you cut will be cut again.

Fight entropy. Leave the codebase better than you found it.

========================================
ENVIRONMENT SETUP (REQUIRED FIRST)
========================================

FOR PYTHON PROJECTS:
1. Check if venv exists. If not, create it: uv venv venv
2. Activate the venv: source venv/bin/activate
3. Install dependencies: uv pip install -r requirements.txt (or scripts/requirements.txt if exists)
4. Install dev tools if not available:
   - uv pip install pytest pytest-cov mypy ruff

FOR NODE.JS PROJECTS:
1. Check Node version in .nvmrc or package.json engines
2. Install dependencies: pnpm install (or npm install if no pnpm)
3. Ensure dev dependencies are installed (jest/vitest, typescript, eslint)

========================================
TASK WORKFLOW
========================================

1. READ CONTEXT:
   - Read prd.json to understand all tasks and their 'passes' status
   - Read progress.txt to see what was done in previous iterations
   - Read review.txt to see any review feedback

2. CHOOSE NEXT TASK (prioritize in this order):
   - Architectural decisions and core abstractions
   - Integration points between modules
   - Unknown unknowns and spike work
   - Standard features and implementation
   - Polish, cleanup, and quick wins
   - Choose a task where 'passes' is false

3. WRITE TESTS FIRST (TDD approach):
   - Before implementing, write failing tests for the feature
   - Tests should cover: happy path, edge cases, error handling
   - Run tests to confirm they fail (red phase)

4. IMPLEMENT THE FEATURE:
   - Keep changes small and focused
   - One logical change per commit
   - Follow existing code patterns in the repo

5. RUN ALL FEEDBACK LOOPS (REQUIRED before commit):

   FOR PYTHON:
   - Type check: python -m mypy <files> --ignore-missing-imports
   - Tests: python -m pytest -v --tb=short
   - Coverage: python -m pytest --cov=. --cov-report=term-missing
   - Lint: python -m ruff check . --fix

   FOR NODE.JS:
   - Type check: pnpm tsc --noEmit (or npx tsc --noEmit)
   - Tests: pnpm test (or npm test)
   - Lint: pnpm lint (or npm run lint)

   DO NOT COMMIT IF ANY FEEDBACK LOOP FAILS.
   Fix issues first, then re-run all checks.

6. UPDATE PRD:
   - Set 'passes' to true for the completed task
   - Add any new subtasks discovered during implementation

7. UPDATE PROGRESS FILE:
   Append to progress.txt:
   - Task completed and PRD item reference
   - Key decisions made and reasoning
   - Files changed
   - Test results summary
   - Any blockers or notes for next iteration
   Keep entries concise.

8. COMMIT YOUR CHANGES:
   - Use descriptive commit message
   - Reference the PRD item ID
   - Only commit if ALL feedback loops pass

9. APPEND REVIEW TO review.txt:
   ## [TASK-ID]: Task Description
   **Status:** PASSED/NEEDS_ATTENTION
   **Tests Written:** (list new tests)
   **Test Results:** (pytest/jest output summary)
   **Type Check:** PASSED/FAILED
   **Lint:** PASSED/FAILED
   **Findings:** Your detailed notes
   **Recommendations:** Any suggestions for future iterations

========================================
RULES
========================================

- ONLY WORK ON A SINGLE TASK PER ITERATION
- Small steps compound into big progress
- Quality over speed - especially when AFK
- Never commit with failing tests or type errors
- Each iteration is a fresh context - progress.txt is your memory
- Git history shows what previous iterations did

If ALL tasks in prd.json have 'passes': true, output <promise>COMPLETE</promise>.")

  echo "$result"
  echo ""

  if [[ "$result" == *"<promise>COMPLETE</promise>"* ]]; then
    echo "=========================================="
    echo "All PRD tasks completed after $i iterations!"
    echo "Review results in review.txt"
    echo "Progress history in progress.txt"
    echo "=========================================="
    exit 0
  fi

  echo "--- Iteration $i complete, starting next fresh context ---"
  echo ""
done

echo "=========================================="
echo "Reached maximum iterations ($1)."
echo "Some tasks may still have 'passes': false."
echo "Check prd.json, progress.txt, and review.txt"
echo "=========================================="
