#!/bin/bash
# Ralph AFK Loop Script with Full Feedback Loops
# Runs Claude in Docker sandbox with comprehensive quality checks
# Supports Python (venv/uv) and Node.js (pnpm) projects

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <iterations>"
  echo "Example: $0 20"
  exit 1
fi

# Ensure review.txt exists
if [ ! -f "review.txt" ]; then
  echo "# Code Review Log" > review.txt
  echo "# Generated by Ralph Loop with Feedback" >> review.txt
  echo "# Date: $(date '+%Y-%m-%d')" >> review.txt
  echo "" >> review.txt
fi

# Ensure progress.txt exists
if [ ! -f "progress.txt" ]; then
  echo "# Progress Log" > progress.txt
  echo "# Generated by Ralph Loop" >> progress.txt
  echo "# Date: $(date '+%Y-%m-%d')" >> progress.txt
  echo "" >> progress.txt
fi

echo "=========================================="
echo "Ralph Loop with Full Feedback Loops"
echo "=========================================="
echo "Iterations: $1"
echo "Model: Claude Opus (latest)"
echo ""
echo "Feedback Loops Enabled:"
echo "  - Type checking (mypy/pyright or tsc)"
echo "  - Unit tests (pytest or jest/vitest)"
echo "  - Linting (ruff/flake8 or eslint)"
echo "  - Pre-commit validation"
echo "  - Browser/UI testing (agent-browser skill)"
echo "=========================================="
echo ""

for ((i=1; i<=$1; i++)); do
  echo "=== Iteration $i of $1 ==="
  echo "Starting fresh Claude context..."
  echo ""

  result=$(docker sandbox run claude --model opus --permission-mode acceptEdits -p "@prd.json @progress.txt @review.txt

========================================
QUALITY EXPECTATIONS
========================================
This codebase will outlive you. Every shortcut you take becomes
someone else's burden. Every hack compounds into technical debt
that slows the whole team down.

You are not just writing code. You are shaping the future of this
project. The patterns you establish will be copied. The corners
you cut will be cut again.

Fight entropy. Leave the codebase better than you found it.

========================================
ENVIRONMENT SETUP (REQUIRED FIRST)
========================================

FOR PYTHON PROJECTS:
1. Check if venv exists. If not, create it: uv venv venv
2. Activate the venv: source venv/bin/activate
3. Install dependencies: uv pip install -r requirements.txt (or scripts/requirements.txt if exists)
4. Install dev tools if not available:
   - uv pip install pytest pytest-cov mypy ruff

FOR NODE.JS PROJECTS:
1. Check Node version in .nvmrc or package.json engines
2. Install dependencies: pnpm install (or npm install if no pnpm)
3. Ensure dev dependencies are installed (jest/vitest, typescript, eslint)

FOR BROWSER TESTING (REQUIRED for UI/frontend tasks):
1. Install agent-browser if not available: npm install -g agent-browser
2. Install Chromium browser: agent-browser install
3. Verify installation: agent-browser --help

========================================
TASK WORKFLOW
========================================

1. READ CONTEXT:
   - Read prd.json to understand all tasks and their 'passes' status
   - Read progress.txt to see what was done in previous iterations
   - Read review.txt to see any review feedback

2. CHOOSE NEXT TASK (prioritize in this order):
   - Architectural decisions and core abstractions
   - Integration points between modules
   - Unknown unknowns and spike work
   - Standard features and implementation
   - UI/UX features requiring browser testing
   - Polish, cleanup, and quick wins
   - Choose a task where 'passes' is false

3. WRITE TESTS FIRST (TDD approach):
   - Before implementing, write failing tests for the feature
   - Tests should cover: happy path, edge cases, error handling
   - Run tests to confirm they fail (red phase)

4. IMPLEMENT THE FEATURE:
   - Keep changes small and focused
   - One logical change per commit
   - Follow existing code patterns in the repo

5. RUN ALL FEEDBACK LOOPS (REQUIRED before commit):

   FOR PYTHON:
   - Type check: python -m mypy <files> --ignore-missing-imports
   - Tests: python -m pytest -v --tb=short
   - Coverage: python -m pytest --cov=. --cov-report=term-missing
   - Lint: python -m ruff check . --fix

   FOR NODE.JS:
   - Type check: pnpm tsc --noEmit (or npx tsc --noEmit)
   - Tests: pnpm test (or npm test)
   - Lint: pnpm lint (or npm run lint)

   FOR UI/BROWSER TESTING (REQUIRED when task has 'tests.visual' in prd.json):

   IMPORTANT: If the task in prd.json has a 'tests.visual' array, you MUST run browser tests.
   Do NOT skip browser tests with excuses like 'requires dev server' - START the dev server!

   Step-by-step browser testing procedure:
   1. Start the dev server in the background:
      cd apps/storefront && pnpm dev &
      sleep 5  # Wait for server to start

   2. Run each visual test from the task's 'tests.visual' array using agent-browser CLI:
      - 'agent-browser: navigate to /drops' → agent-browser open http://localhost:4321/drops
      - 'agent-browser: screenshot drops listing' → agent-browser screenshot ./screenshots/drops-listing.png
      - 'agent-browser: click Shop Now' → agent-browser snapshot -i && agent-browser click @e1
      - 'agent-browser: verify element visible' → agent-browser snapshot -i (check output)

   3. Common agent-browser commands:
      - agent-browser open <url>           # Navigate to URL
      - agent-browser snapshot -i          # Get interactive elements with refs (@e1, @e2, etc.)
      - agent-browser click @e1            # Click element by ref
      - agent-browser fill @e2 'text'      # Fill input by ref
      - agent-browser screenshot path.png  # Take screenshot
      - agent-browser screenshot --full    # Full page screenshot
      - agent-browser get text @e1         # Get element text
      - agent-browser wait --load networkidle  # Wait for page load

   4. After testing, stop the dev server:
      pkill -f 'astro dev' || true

   5. Report results in review.txt under 'Browser Tests:' - PASSED or FAILED with details

   DO NOT COMMIT IF ANY FEEDBACK LOOP FAILS.
   Fix issues first, then re-run all checks.

6. UPDATE PRD:
   - Set 'passes' to true for the completed task
   - Add any new subtasks discovered during implementation

7. UPDATE PROGRESS FILE:
   Append to progress.txt:
   - Task completed and PRD item reference
   - Key decisions made and reasoning
   - Files changed
   - Test results summary
   - Any blockers or notes for next iteration
   Keep entries concise.

8. COMMIT YOUR CHANGES:
   - Stage all changes: git add -A
   - Use descriptive commit message referencing the PRD item ID
   - Only commit if ALL feedback loops pass
   - IMPORTANT: Do NOT add Co-Authored-By tags to commits

   IF GIT COMMIT FAILS DUE TO PRE-COMMIT HOOKS:
   - Read the error output carefully
   - The pre-commit hooks run: lint-staged, typecheck, prettier
   - Fix ALL issues reported by the hooks
   - Stage the fixes: git add -A
   - Re-run git commit with the same message
   - REPEAT until the commit succeeds
   - Do NOT give up or skip - the commit MUST succeed before moving on
   - Log any persistent issues to progress.txt for debugging

9. APPEND REVIEW TO review.txt:
   ## [TASK-ID]: Task Description
   **Status:** PASSED/NEEDS_ATTENTION
   **Tests Written:** (list new tests)
   **Test Results:** (pytest/jest output summary)
   **Type Check:** PASSED/FAILED
   **Lint:** PASSED/FAILED
   **Browser Tests:** PASSED/FAILED/N/A
     - If task has 'tests.visual' array: MUST be PASSED or FAILED (not SKIPPED!)
     - If task has no 'tests.visual' array: N/A
     - Include: which visual tests were run, screenshots taken, any failures
   **Findings:** Your detailed notes
   **Recommendations:** Any suggestions for future iterations

========================================
RULES
========================================

- ONLY WORK ON A SINGLE TASK PER ITERATION
- Small steps compound into big progress
- Quality over speed - especially when AFK
- Never commit with failing tests or type errors
- Each iteration is a fresh context - progress.txt is your memory
- Git history shows what previous iterations did
- BROWSER TESTS ARE MANDATORY: If task has 'tests.visual' in prd.json, you MUST:
  1. Install agent-browser if needed: npm install -g agent-browser && agent-browser install
  2. Start the dev server: cd apps/storefront && pnpm dev &
  3. Run ALL visual tests listed in the task's 'tests.visual' array
  4. Report PASSED or FAILED - NEVER report SKIPPED for visual tests

If ALL tasks in prd.json have 'passes': true, output <promise>COMPLETE</promise>.")

  echo "$result"
  echo ""

  # Push changes committed by Claude inside Docker
  echo "--- Pushing changes from iteration $i ---"
  if git push origin HEAD; then
    echo "Successfully pushed changes"
  else
    echo "Warning: Push failed (will retry next iteration)"
  fi
  echo ""

  if [[ "$result" == *"<promise>COMPLETE</promise>"* ]]; then
    echo "=========================================="
    echo "All PRD tasks completed after $i iterations!"
    echo "Review results in review.txt"
    echo "Progress history in progress.txt"
    echo "=========================================="
    exit 0
  fi

  echo "--- Iteration $i complete, starting next fresh context ---"
  echo ""
done

# Final push for any remaining commits
echo "--- Final push ---"
git push origin HEAD || echo "Warning: Final push failed"

echo "=========================================="
echo "Reached maximum iterations ($1)."
echo "Some tasks may still have 'passes': false."
echo "Check prd.json, progress.txt, and review.txt"
echo "=========================================="
